import React from 'react'

import { Helmet } from 'react-helmet'

import './loginscreen2.css'

const Loginscreen2 = (props) => {
  return (
    <div className="loginscreen2-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="loginscreen2-loginscreen">
        <div className="loginscreen2-status-bari-phone13">
          <div className="loginscreen2-left-side">
            <div className="loginscreen2-frame-status-bartime">
              <span className="loginscreen2-text1 DefaultBoldBody">
                <span>9:41</span>
              </span>
            </div>
          </div>
          <div className="loginscreen2-right-side">
            <div className="loginscreen2-battery">
              <img
                src="/external/outlinei391-zs1f.svg"
                alt="OutlineI391"
                className="loginscreen2-outline"
              />
              <img
                src="/external/batteryendi391-tdek.svg"
                alt="BatteryEndI391"
                className="loginscreen2-battery-end"
              />
              <img
                src="/external/filli391-g1w.svg"
                alt="FillI391"
                className="loginscreen2-fill"
              />
            </div>
            <img
              src="/external/wifii391-y6we.svg"
              alt="WifiI391"
              className="loginscreen2-wifi"
            />
            <img
              src="/external/iconmobilesignali391-gez.svg"
              alt="IconMobileSignalI391"
              className="loginscreen2-icon-mobile-signal"
            />
          </div>
        </div>
        <img
          src="/external/rectangle243912-ul66-200h.png"
          alt="Rectangle243912"
          className="loginscreen2-rectangle24"
        />
        <div className="loginscreen2-byerafiki">
          <div className="loginscreen2-backgroundcomplete">
            <img
              src="/external/vector3912-buu.svg"
              alt="Vector3912"
              className="loginscreen2-vector10"
            />
            <img
              src="/external/vector3912-juof.svg"
              alt="Vector3912"
              className="loginscreen2-vector11"
            />
            <img
              src="/external/vector3912-0lcyb.svg"
              alt="Vector3912"
              className="loginscreen2-vector12"
            />
            <img
              src="/external/vector3912-gzba.svg"
              alt="Vector3912"
              className="loginscreen2-vector13"
            />
            <img
              src="/external/vector3912-fsq.svg"
              alt="Vector3912"
              className="loginscreen2-vector14"
            />
          </div>
          <div className="loginscreen2-shadow">
            <img
              src="/external/path3912-dysi.svg"
              alt="path3912"
              className="loginscreen2-path"
            />
          </div>
          <div className="loginscreen2-character1">
            <img
              src="/external/vector3912-qdfv.svg"
              alt="Vector3912"
              className="loginscreen2-vector15"
            />
            <img
              src="/external/vector3912-0h5r.svg"
              alt="Vector3912"
              className="loginscreen2-vector16"
            />
            <img
              src="/external/vector3912-rfuk.svg"
              alt="Vector3912"
              className="loginscreen2-vector17"
            />
            <img
              src="/external/vector3912-ufy.svg"
              alt="Vector3912"
              className="loginscreen2-vector18"
            />
            <img
              src="/external/vector3912-06og.svg"
              alt="Vector3912"
              className="loginscreen2-vector19"
            />
            <img
              src="/external/vector3913-lfw8.svg"
              alt="Vector3913"
              className="loginscreen2-vector20"
            />
            <img
              src="/external/vector3913-jbta.svg"
              alt="Vector3913"
              className="loginscreen2-vector21"
            />
            <img
              src="/external/vector3913-sin9.svg"
              alt="Vector3913"
              className="loginscreen2-vector22"
            />
            <img
              src="/external/vector3913-hibo.svg"
              alt="Vector3913"
              className="loginscreen2-vector23"
            />
            <img
              src="/external/vector3913-rzjn.svg"
              alt="Vector3913"
              className="loginscreen2-vector24"
            />
            <img
              src="/external/vector3913-xhz.svg"
              alt="Vector3913"
              className="loginscreen2-vector25"
            />
            <img
              src="/external/vector3913-9xa.svg"
              alt="Vector3913"
              className="loginscreen2-vector26"
            />
            <img
              src="/external/vector3913-ogx.svg"
              alt="Vector3913"
              className="loginscreen2-vector27"
            />
            <img
              src="/external/vector3913-k99.svg"
              alt="Vector3913"
              className="loginscreen2-vector28"
            />
            <img
              src="/external/vector3913-1cp.svg"
              alt="Vector3913"
              className="loginscreen2-vector29"
            />
            <img
              src="/external/vector3913-bs3a.svg"
              alt="Vector3913"
              className="loginscreen2-vector30"
            />
            <img
              src="/external/vector3913-qvh8.svg"
              alt="Vector3913"
              className="loginscreen2-vector31"
            />
            <img
              src="/external/vector3913-ud7a.svg"
              alt="Vector3913"
              className="loginscreen2-vector32"
            />
            <img
              src="/external/vector3913-841g.svg"
              alt="Vector3913"
              className="loginscreen2-vector33"
            />
            <img
              src="/external/vector3913-7w1.svg"
              alt="Vector3913"
              className="loginscreen2-vector34"
            />
            <img
              src="/external/vector3913-jsqn.svg"
              alt="Vector3913"
              className="loginscreen2-vector35"
            />
            <img
              src="/external/vector3913-rs7.svg"
              alt="Vector3913"
              className="loginscreen2-vector36"
            />
            <img
              src="/external/vector3913-8c2d.svg"
              alt="Vector3913"
              className="loginscreen2-vector37"
            />
            <img
              src="/external/vector3913-iago.svg"
              alt="Vector3913"
              className="loginscreen2-vector38"
            />
            <img
              src="/external/vector3913-pb0or.svg"
              alt="Vector3913"
              className="loginscreen2-vector39"
            />
            <img
              src="/external/vector3913-kjsk.svg"
              alt="Vector3913"
              className="loginscreen2-vector40"
            />
            <img
              src="/external/vector3913-7wrx.svg"
              alt="Vector3913"
              className="loginscreen2-vector41"
            />
            <img
              src="/external/vector3913-2j7k.svg"
              alt="Vector3913"
              className="loginscreen2-vector42"
            />
            <img
              src="/external/vector3913-t3pj.svg"
              alt="Vector3913"
              className="loginscreen2-vector43"
            />
            <img
              src="/external/vector3913-fz7.svg"
              alt="Vector3913"
              className="loginscreen2-vector44"
            />
            <img
              src="/external/vector3913-5y1.svg"
              alt="Vector3913"
              className="loginscreen2-vector45"
            />
          </div>
          <div className="loginscreen2-character2">
            <img
              src="/external/vector3913-f9ff.svg"
              alt="Vector3913"
              className="loginscreen2-vector46"
            />
            <img
              src="/external/vector3913-1ux8.svg"
              alt="Vector3913"
              className="loginscreen2-vector47"
            />
            <img
              src="/external/vector3913-t0js.svg"
              alt="Vector3913"
              className="loginscreen2-vector48"
            />
            <img
              src="/external/vector3913-l74t.svg"
              alt="Vector3913"
              className="loginscreen2-vector49"
            />
            <img
              src="/external/vector3913-p7nt.svg"
              alt="Vector3913"
              className="loginscreen2-vector50"
            />
            <img
              src="/external/vector3913-s6pe.svg"
              alt="Vector3913"
              className="loginscreen2-vector51"
            />
            <img
              src="/external/vector3913-k8zo.svg"
              alt="Vector3913"
              className="loginscreen2-vector52"
            />
            <img
              src="/external/vector3913-qej.svg"
              alt="Vector3913"
              className="loginscreen2-vector53"
            />
            <img
              src="/external/vector3913-me7.svg"
              alt="Vector3913"
              className="loginscreen2-vector54"
            />
            <img
              src="/external/vector3913-afxj6.svg"
              alt="Vector3913"
              className="loginscreen2-vector55"
            />
            <img
              src="/external/vector3913-ve6i.svg"
              alt="Vector3913"
              className="loginscreen2-vector56"
            />
            <img
              src="/external/vector3913-i5o8.svg"
              alt="Vector3913"
              className="loginscreen2-vector57"
            />
            <img
              src="/external/vector3913-e2en.svg"
              alt="Vector3913"
              className="loginscreen2-vector58"
            />
            <img
              src="/external/vector3913-npk.svg"
              alt="Vector3913"
              className="loginscreen2-vector59"
            />
            <img
              src="/external/vector3913-bsbv.svg"
              alt="Vector3913"
              className="loginscreen2-vector60"
            />
            <img
              src="/external/vector3913-80rm.svg"
              alt="Vector3913"
              className="loginscreen2-vector61"
            />
            <img
              src="/external/vector3913-e8n7.svg"
              alt="Vector3913"
              className="loginscreen2-vector62"
            />
            <img
              src="/external/vector3913-jv5o.svg"
              alt="Vector3913"
              className="loginscreen2-vector63"
            />
            <img
              src="/external/vector3913-31bi.svg"
              alt="Vector3913"
              className="loginscreen2-vector64"
            />
            <img
              src="/external/vector3913-nk2f.svg"
              alt="Vector3913"
              className="loginscreen2-vector65"
            />
            <img
              src="/external/vector3913-yc2.svg"
              alt="Vector3913"
              className="loginscreen2-vector66"
            />
            <img
              src="/external/vector3913-d9ki.svg"
              alt="Vector3913"
              className="loginscreen2-vector67"
            />
            <img
              src="/external/vector3913-uo54.svg"
              alt="Vector3913"
              className="loginscreen2-vector68"
            />
            <img
              src="/external/vector3913-r76p.svg"
              alt="Vector3913"
              className="loginscreen2-vector69"
            />
            <img
              src="/external/vector3913-4yc.svg"
              alt="Vector3913"
              className="loginscreen2-vector70"
            />
            <img
              src="/external/vector3913-153d.svg"
              alt="Vector3913"
              className="loginscreen2-vector71"
            />
            <img
              src="/external/vector3913-fog9.svg"
              alt="Vector3913"
              className="loginscreen2-vector72"
            />
            <img
              src="/external/vector3913-nak.svg"
              alt="Vector3913"
              className="loginscreen2-vector73"
            />
            <img
              src="/external/vector3913-0gnq.svg"
              alt="Vector3913"
              className="loginscreen2-vector74"
            />
            <img
              src="/external/vector3913-odko.svg"
              alt="Vector3913"
              className="loginscreen2-vector75"
            />
            <img
              src="/external/vector3913-k4fk.svg"
              alt="Vector3913"
              className="loginscreen2-vector76"
            />
            <img
              src="/external/vector3913-yua.svg"
              alt="Vector3913"
              className="loginscreen2-vector77"
            />
            <img
              src="/external/vector3913-6wph.svg"
              alt="Vector3913"
              className="loginscreen2-vector78"
            />
            <img
              src="/external/vector3913-g6oy.svg"
              alt="Vector3913"
              className="loginscreen2-vector79"
            />
            <img
              src="/external/vector3913-jgvje.svg"
              alt="Vector3913"
              className="loginscreen2-vector80"
            />
            <img
              src="/external/vector3913-zu3o.svg"
              alt="Vector3913"
              className="loginscreen2-vector81"
            />
            <img
              src="/external/vector3913-g3pi.svg"
              alt="Vector3913"
              className="loginscreen2-vector82"
            />
            <img
              src="/external/vector3913-sm0q.svg"
              alt="Vector3913"
              className="loginscreen2-vector83"
            />
            <img
              src="/external/vector3913-iyx5.svg"
              alt="Vector3913"
              className="loginscreen2-vector84"
            />
            <img
              src="/external/vector3913-ya9g3.svg"
              alt="Vector3913"
              className="loginscreen2-vector85"
            />
            <img
              src="/external/vector3913-avk.svg"
              alt="Vector3913"
              className="loginscreen2-vector86"
            />
            <img
              src="/external/vector3913-cck9.svg"
              alt="Vector3913"
              className="loginscreen2-vector87"
            />
            <img
              src="/external/vector3913-2kih.svg"
              alt="Vector3913"
              className="loginscreen2-vector88"
            />
            <img
              src="/external/vector3913-ul98.svg"
              alt="Vector3913"
              className="loginscreen2-vector89"
            />
            <img
              src="/external/vector3913-5e7k.svg"
              alt="Vector3913"
              className="loginscreen2-vector90"
            />
            <img
              src="/external/vector3913-068.svg"
              alt="Vector3913"
              className="loginscreen2-vector91"
            />
            <img
              src="/external/vector3913-nofa.svg"
              alt="Vector3913"
              className="loginscreen2-vector92"
            />
            <img
              src="/external/vector3913-15oe.svg"
              alt="Vector3913"
              className="loginscreen2-vector93"
            />
            <img
              src="/external/vector3913-yj9d.svg"
              alt="Vector3913"
              className="loginscreen2-vector94"
            />
          </div>
        </div>
        <div className="loginscreen2-icon">
          <span className="loginscreen2-text3"></span>
        </div>
      </div>
    </div>
  )
}

export default Loginscreen2
