import React from 'react'

import { Helmet } from 'react-helmet'

import './loginscreen.css'

const Loginscreen = (props) => {
  return (
    <div className="loginscreen-container">
      <Helmet>
        <title>exported project</title>
      </Helmet>
      <div className="loginscreen-loginscreen">
        <div className="loginscreen-status-bari-phone13">
          <div className="loginscreen-left-side">
            <div className="loginscreen-frame-status-bartime">
              <span className="loginscreen-text10 DefaultBoldBody">
                <span>9:41</span>
              </span>
            </div>
          </div>
          <div className="loginscreen-right-side">
            <div className="loginscreen-battery">
              <img
                src="/external/outlinei125-42f.svg"
                alt="OutlineI125"
                className="loginscreen-outline"
              />
              <img
                src="/external/batteryendi125-414.svg"
                alt="BatteryEndI125"
                className="loginscreen-battery-end"
              />
              <img
                src="/external/filli125-nram.svg"
                alt="FillI125"
                className="loginscreen-fill"
              />
            </div>
            <img
              src="/external/wifii125-htq7.svg"
              alt="WifiI125"
              className="loginscreen-wifi"
            />
            <img
              src="/external/iconmobilesignali125-hji.svg"
              alt="IconMobileSignalI125"
              className="loginscreen-icon-mobile-signal"
            />
          </div>
        </div>
        <img
          src="/external/rectangle241259-gm25-200h.png"
          alt="Rectangle241259"
          className="loginscreen-rectangle24"
        />
        <div className="loginscreen-byerafiki">
          <div className="loginscreen-backgroundcomplete">
            <img
              src="/external/vector1260-2wzd.svg"
              alt="Vector1260"
              className="loginscreen-vector10"
            />
            <img
              src="/external/vector1260-m5i6.svg"
              alt="Vector1260"
              className="loginscreen-vector11"
            />
            <img
              src="/external/vector1260-c1m.svg"
              alt="Vector1260"
              className="loginscreen-vector12"
            />
            <img
              src="/external/vector1260-wfwe.svg"
              alt="Vector1260"
              className="loginscreen-vector13"
            />
            <img
              src="/external/vector1260-xt6.svg"
              alt="Vector1260"
              className="loginscreen-vector14"
            />
            <img
              src="/external/vector1260-e14.svg"
              alt="Vector1260"
              className="loginscreen-vector15"
            />
            <img
              src="/external/vector1260-uij4.svg"
              alt="Vector1260"
              className="loginscreen-vector16"
            />
          </div>
          <div className="loginscreen-shadow">
            <img
              src="/external/path1261-b713.svg"
              alt="path1261"
              className="loginscreen-path"
            />
          </div>
          <div className="loginscreen-character1">
            <img
              src="/external/vector1261-cfaq.svg"
              alt="Vector1261"
              className="loginscreen-vector17"
            />
            <img
              src="/external/vector1261-avgp.svg"
              alt="Vector1261"
              className="loginscreen-vector18"
            />
            <img
              src="/external/vector1261-s1si.svg"
              alt="Vector1261"
              className="loginscreen-vector19"
            />
            <img
              src="/external/vector1261-ef9.svg"
              alt="Vector1261"
              className="loginscreen-vector20"
            />
            <img
              src="/external/vector1261-cmiq.svg"
              alt="Vector1261"
              className="loginscreen-vector21"
            />
            <img
              src="/external/vector1261-1i5h.svg"
              alt="Vector1261"
              className="loginscreen-vector22"
            />
            <img
              src="/external/vector1261-m36.svg"
              alt="Vector1261"
              className="loginscreen-vector23"
            />
            <img
              src="/external/vector1261-mu1r.svg"
              alt="Vector1261"
              className="loginscreen-vector24"
            />
            <img
              src="/external/vector1262-icx.svg"
              alt="Vector1262"
              className="loginscreen-vector25"
            />
            <img
              src="/external/vector1262-uwlo.svg"
              alt="Vector1262"
              className="loginscreen-vector26"
            />
            <img
              src="/external/vector1262-9zk.svg"
              alt="Vector1262"
              className="loginscreen-vector27"
            />
            <img
              src="/external/vector1262-7yag.svg"
              alt="Vector1262"
              className="loginscreen-vector28"
            />
            <img
              src="/external/vector1262-9809.svg"
              alt="Vector1262"
              className="loginscreen-vector29"
            />
            <img
              src="/external/vector1262-3iof.svg"
              alt="Vector1262"
              className="loginscreen-vector30"
            />
            <img
              src="/external/vector1262-y3h7.svg"
              alt="Vector1262"
              className="loginscreen-vector31"
            />
            <img
              src="/external/vector1262-8wc.svg"
              alt="Vector1262"
              className="loginscreen-vector32"
            />
            <img
              src="/external/vector1262-4wmd.svg"
              alt="Vector1262"
              className="loginscreen-vector33"
            />
            <img
              src="/external/vector1262-95wg.svg"
              alt="Vector1262"
              className="loginscreen-vector34"
            />
            <img
              src="/external/vector1263-zf2.svg"
              alt="Vector1263"
              className="loginscreen-vector35"
            />
            <img
              src="/external/vector1263-ofyg.svg"
              alt="Vector1263"
              className="loginscreen-vector36"
            />
            <img
              src="/external/vector1263-40ub.svg"
              alt="Vector1263"
              className="loginscreen-vector37"
            />
            <img
              src="/external/vector1263-l23i.svg"
              alt="Vector1263"
              className="loginscreen-vector38"
            />
            <img
              src="/external/vector1263-d5x2.svg"
              alt="Vector1263"
              className="loginscreen-vector39"
            />
            <img
              src="/external/vector1263-22ie.svg"
              alt="Vector1263"
              className="loginscreen-vector40"
            />
            <img
              src="/external/vector1263-adxv.svg"
              alt="Vector1263"
              className="loginscreen-vector41"
            />
            <img
              src="/external/vector1263-y7mo.svg"
              alt="Vector1263"
              className="loginscreen-vector42"
            />
            <img
              src="/external/vector1263-q33.svg"
              alt="Vector1263"
              className="loginscreen-vector43"
            />
            <img
              src="/external/vector1263-aczb.svg"
              alt="Vector1263"
              className="loginscreen-vector44"
            />
            <img
              src="/external/vector1264-t7k.svg"
              alt="Vector1264"
              className="loginscreen-vector45"
            />
            <img
              src="/external/vector1264-pkop.svg"
              alt="Vector1264"
              className="loginscreen-vector46"
            />
            <img
              src="/external/vector1264-p3z.svg"
              alt="Vector1264"
              className="loginscreen-vector47"
            />
          </div>
          <div className="loginscreen-character2">
            <img
              src="/external/vector1264-y5ch.svg"
              alt="Vector1264"
              className="loginscreen-vector48"
            />
            <img
              src="/external/vector1264-5pwc.svg"
              alt="Vector1264"
              className="loginscreen-vector49"
            />
            <img
              src="/external/vector1264-yj9h.svg"
              alt="Vector1264"
              className="loginscreen-vector50"
            />
            <img
              src="/external/vector1264-eevu.svg"
              alt="Vector1264"
              className="loginscreen-vector51"
            />
            <img
              src="/external/vector1264-5a.svg"
              alt="Vector1264"
              className="loginscreen-vector52"
            />
            <img
              src="/external/vector1264-q74.svg"
              alt="Vector1264"
              className="loginscreen-vector53"
            />
            <img
              src="/external/vector1265-bit.svg"
              alt="Vector1265"
              className="loginscreen-vector54"
            />
            <img
              src="/external/vector1265-wbx8.svg"
              alt="Vector1265"
              className="loginscreen-vector55"
            />
            <img
              src="/external/vector1265-brkx.svg"
              alt="Vector1265"
              className="loginscreen-vector56"
            />
            <img
              src="/external/vector1265-6oow.svg"
              alt="Vector1265"
              className="loginscreen-vector57"
            />
            <img
              src="/external/vector1265-vkd.svg"
              alt="Vector1265"
              className="loginscreen-vector58"
            />
            <img
              src="/external/vector1265-kmtd.svg"
              alt="Vector1265"
              className="loginscreen-vector59"
            />
            <img
              src="/external/vector1265-b4q5.svg"
              alt="Vector1265"
              className="loginscreen-vector60"
            />
            <img
              src="/external/vector1265-my8s.svg"
              alt="Vector1265"
              className="loginscreen-vector61"
            />
            <img
              src="/external/vector1265-frz9.svg"
              alt="Vector1265"
              className="loginscreen-vector62"
            />
            <img
              src="/external/vector1265-p32f.svg"
              alt="Vector1265"
              className="loginscreen-vector63"
            />
            <img
              src="/external/vector1266-glcn.svg"
              alt="Vector1266"
              className="loginscreen-vector64"
            />
            <img
              src="/external/vector1266-l7mn.svg"
              alt="Vector1266"
              className="loginscreen-vector65"
            />
            <img
              src="/external/vector1266-s1q.svg"
              alt="Vector1266"
              className="loginscreen-vector66"
            />
            <img
              src="/external/vector1266-6iz5.svg"
              alt="Vector1266"
              className="loginscreen-vector67"
            />
            <img
              src="/external/vector1266-td4l.svg"
              alt="Vector1266"
              className="loginscreen-vector68"
            />
            <img
              src="/external/vector1266-8r3.svg"
              alt="Vector1266"
              className="loginscreen-vector69"
            />
            <img
              src="/external/vector1266-kfqb.svg"
              alt="Vector1266"
              className="loginscreen-vector70"
            />
            <img
              src="/external/vector1266-cl1.svg"
              alt="Vector1266"
              className="loginscreen-vector71"
            />
            <img
              src="/external/vector1266-8bes.svg"
              alt="Vector1266"
              className="loginscreen-vector72"
            />
            <img
              src="/external/vector1266-8wvi.svg"
              alt="Vector1266"
              className="loginscreen-vector73"
            />
            <img
              src="/external/vector1267-gy2.svg"
              alt="Vector1267"
              className="loginscreen-vector74"
            />
            <img
              src="/external/vector1267-z1fi.svg"
              alt="Vector1267"
              className="loginscreen-vector75"
            />
            <img
              src="/external/vector1267-o1v.svg"
              alt="Vector1267"
              className="loginscreen-vector76"
            />
            <img
              src="/external/vector1267-q6sc.svg"
              alt="Vector1267"
              className="loginscreen-vector77"
            />
            <img
              src="/external/vector1267-n5yk.svg"
              alt="Vector1267"
              className="loginscreen-vector78"
            />
            <img
              src="/external/vector1267-74f.svg"
              alt="Vector1267"
              className="loginscreen-vector79"
            />
            <img
              src="/external/vector1267-jzh.svg"
              alt="Vector1267"
              className="loginscreen-vector80"
            />
            <img
              src="/external/vector1267-9uz.svg"
              alt="Vector1267"
              className="loginscreen-vector81"
            />
            <img
              src="/external/vector1267-5a8p.svg"
              alt="Vector1267"
              className="loginscreen-vector82"
            />
            <img
              src="/external/vector1267-6gtg.svg"
              alt="Vector1267"
              className="loginscreen-vector83"
            />
            <img
              src="/external/vector1268-39l.svg"
              alt="Vector1268"
              className="loginscreen-vector84"
            />
            <img
              src="/external/vector1268-tifb.svg"
              alt="Vector1268"
              className="loginscreen-vector85"
            />
            <img
              src="/external/vector1268-h1km.svg"
              alt="Vector1268"
              className="loginscreen-vector86"
            />
            <img
              src="/external/vector1268-2sj.svg"
              alt="Vector1268"
              className="loginscreen-vector87"
            />
            <img
              src="/external/vector1268-dkhw.svg"
              alt="Vector1268"
              className="loginscreen-vector88"
            />
            <img
              src="/external/vector1268-k28.svg"
              alt="Vector1268"
              className="loginscreen-vector89"
            />
            <img
              src="/external/vector1268-lmfc.svg"
              alt="Vector1268"
              className="loginscreen-vector90"
            />
            <img
              src="/external/vector1268-50l.svg"
              alt="Vector1268"
              className="loginscreen-vector91"
            />
            <img
              src="/external/vector1268-pq.svg"
              alt="Vector1268"
              className="loginscreen-vector92"
            />
            <img
              src="/external/vector1268-h4z.svg"
              alt="Vector1268"
              className="loginscreen-vector93"
            />
            <img
              src="/external/vector1269-94ur.svg"
              alt="Vector1269"
              className="loginscreen-vector94"
            />
            <img
              src="/external/vector1269-kaus.svg"
              alt="Vector1269"
              className="loginscreen-vector95"
            />
            <img
              src="/external/vector1269-28je.svg"
              alt="Vector1269"
              className="loginscreen-vector96"
            />
          </div>
        </div>
        <div className="loginscreen-icon1">
          <span className="loginscreen-text12"></span>
        </div>
        <div className="loginscreen-frame16">
          <div className="loginscreen-text-styles1">
            <span className="loginscreen-text13 Heading">
              <span>Login</span>
            </span>
          </div>
          <div className="loginscreen-frame15">
            <div className="loginscreen-frame12">
              <div className="loginscreen-icon2">
                <span className="loginscreen-text15 SingleLineBodyBase">@</span>
              </div>
              <div className="loginscreen-text-styles2">
                <span className="loginscreen-text16 SingleLineBodyBase">
                  <span>Email</span>
                </span>
              </div>
            </div>
            <div className="loginscreen-frame14">
              <div className="loginscreen-icon3">
                <span className="loginscreen-text18"></span>
              </div>
              <div className="loginscreen-text-styles3">
                <span className="loginscreen-text19 SingleLineBodyBase">
                  <span>Password</span>
                </span>
              </div>
            </div>
            <div className="loginscreen-text-styles4">
              <span className="loginscreen-text21 BodySmall">
                <span> Forgot Password?</span>
              </span>
            </div>
          </div>
        </div>
        <div className="loginscreen-frame18">
          <button className="loginscreen-buttons1">
            <span className="loginscreen-text23 Body-14pxMedium">
              <span>Continue</span>
            </span>
          </button>
          <div className="loginscreen-frame17">
            <img
              src="/external/line131270-8r9l.svg"
              alt="Line131270"
              className="loginscreen-line13"
            />
            <div className="loginscreen-text-styles5">
              <span className="loginscreen-text25">
                <span>OR</span>
              </span>
            </div>
            <img
              src="/external/line141271-f50c.svg"
              alt="Line141271"
              className="loginscreen-line14"
            />
          </div>
          <button className="loginscreen-buttons2">
            <img
              src="/external/svg011271-l82i.svg"
              alt="svg011271"
              className="loginscreen-svg01"
            />
            <span className="loginscreen-text27 Body-14pxMedium">
              <span>Login with Google</span>
            </span>
          </button>
        </div>
      </div>
    </div>
  )
}

export default Loginscreen
